Repository jannaem/M151-LB2_Blaser-Esteban, pull requests merged in 2022-10, with the labels that each got.

#6 implemeted method "to delete task by id" and "save task"
  backend/src/main/java/todoapp/backend/task/TaskController.java
  backend/src/main/java/todoapp/backend/task/TaskServiceImpl.java
Labels: feature

#7 Feature/test task
  backend/build.gradle
  backend/src/main/java/todoapp/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/todoapp/backend/TaskControllerTest.java
  backend/src/test/resources/TestData.sql
Labels: testing

#8 Feature/basic structure
  frontend/.env
  frontend/.gitignore copy
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/atoms/.gitkeep
  frontend/src/constants/Cookies.ts
  frontend/src/index.tsx
  frontend/src/models/Cookie.ts
  frontend/src/models/Principal.ts
  frontend/src/models/Roles.ts
  frontend/src/models/Task.ts
  frontend/src/models/ToDo.ts
  frontend/src/models/ToDoDTO.ts
  frontend/src/models/User.ts
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/services/ApiService.ts
  frontend/src/services/AuthenticationService.ts
  frontend/src/setupTests.ts
  frontend/src/utils/B64Utility.ts
  frontend/src/utils/CookieUtility.ts
  frontend/src/utils/JWTUtility.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: enhancement, feature

#9 API Service
  frontend/src/services/TaskService.ts
  frontend/src/services/ToDoListService.ts
Labels: enhancement

#10 implemented authentication context
  frontend/src/constants/AuthenticationContext.tsx
Labels: enhancement

#11 added Snackbar messages
  frontend/package.json
  frontend/src/components/atoms/MuiSnackbar/MuiSnackbar.css
  frontend/src/components/atoms/MuiSnackbar/MuiSnackbar.tsx
  frontend/src/contexts/ContextErrors.tsx
  frontend/src/contexts/SnackbarContext.tsx
  frontend/yarn.lock
Labels: enhancement

#13 tested user and todolist controller
  backend/src/test/java/todoapp/backend/ToDoListControllerTest.java
  backend/src/test/java/todoapp/backend/UserControllerTest.java
Labels: testing

#14 removed unnecesary files and added a theme for the project from MUI"
  frontend/README.md
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/logo.svg
  frontend/theme.ts
  frontend/yarn.lock
Labels: enhancement

#15 added molecules folder to avoid merge conflict by creating molecules"
  frontend/src/components/molecules/.gitkeep
Labels: enhancement

#16 added a searchfield and addbutton atoms
  frontend/package.json
  frontend/src/components/atoms/.gitkeep
  frontend/src/components/atoms/AddButton/AddButton.tsx
  frontend/src/components/atoms/Searchfield/Searchfield.tsx
  frontend/yarn.lock
Labels: feature

#19 added list view for todolist"
  frontend/src/components/molecules/ToDoList/ToDoList.css
  frontend/src/components/molecules/ToDoList/ToDoList.tsx
Labels: feature

#18 Feature/authentication
  frontend/package.json
  frontend/src/components/atoms/ProtectedRoute/ProtectedRoute.tsx
  frontend/src/contexts/AuthenticationContext.tsx
  frontend/yarn.lock
Labels: enhancement

#22 implemented registration site and validation
  frontend/src/Validation.ts
  frontend/src/components/Pages/registration/Registration.css
  frontend/src/components/Pages/registration/Registration.tsx
  frontend/src/components/atoms/Divider/Divider.css
  frontend/src/components/atoms/Divider/Divider.tsx
  frontend/src/models/Form.ts
Labels: feature
